// packages/ui-vue/src/components/primitives/static/Loading/Loader.vue
<script lang="ts">
import { warnInDevelopment } from '@hoite-dev/diagnostics';
import {
  type LoadingColor,
  type LoadingSize,
  loaderVariants,
  pickAriaAndDataAttributes,
} from '@hoite-dev/ui';
import { computed, defineComponent, type PropType, watchEffect } from 'vue';

type LoaderBaseProps = {
  color?: LoadingColor;
  id?: string;
  size?: LoadingSize;
};

function isPresent(value: unknown): boolean {
  if (typeof value !== 'string') {
    return false;
  }

  return value.trim().length > 0;
}

export type LoaderProps = LoaderBaseProps;

export default defineComponent({
  inheritAttrs: false,
  props: {
    color: {
      required: false,
      type: String as PropType<LoadingColor>,
    },
    id: {
      required: false,
      type: String,
    },
    size: {
      required: false,
      type: String as PropType<LoadingSize>,
    },
  },
  setup(props: Readonly<LoaderBaseProps>, { attrs }) {
    const className = computed(() =>
      loaderVariants({
        class: attrs.class,
        color: props.color,
        size: props.size,
      }),
    );
    const restAttrs = computed(() => pickAriaAndDataAttributes(attrs));

    watchEffect(() => {
      const ariaHidden = restAttrs.value['aria-hidden'];

      if (ariaHidden === true || ariaHidden === 'true') {
        return;
      }

      const ariaLabel = restAttrs.value['aria-label'];
      const ariaLabelledBy = restAttrs.value['aria-labelledby'];

      if (!isPresent(ariaLabel) && !isPresent(ariaLabelledBy)) {
        warnInDevelopment(
          '[Loader] Accessible loading text is missing. Provide `aria-label` or `aria-labelledby`, or mark the loader as decorative with `aria-hidden`.',
        );
      }
    });

    return {
      className,
      restAttrs,
    };
  },
});
</script>

<template>
  <span
    v-bind="restAttrs"
    :class="className"
    :id="id"
    role="status"
  />
</template>

// packages/ui-react/src/components/primitives/static/Loading/Loader.tsx
import { warnInDevelopment } from '@hoite-dev/diagnostics';
import { type LoadingColor, type LoadingSize, loaderVariants } from '@hoite-dev/ui';
import { type ComponentPropsWithoutRef, type ReactElement, useEffect } from 'react';

type LoaderBaseProps = {
  color?: LoadingColor;
  size?: LoadingSize;
};

export type LoaderProps = LoaderBaseProps & Omit<ComponentPropsWithoutRef<'span'>, 'color'>;

function isPresent(value: string | undefined): boolean {
  if (value === undefined) {
    return false;
  }

  return value.trim().length > 0;
}

export function Loader({ className, color, size, ...restProps }: LoaderProps): ReactElement {
  const ariaHidden = restProps['aria-hidden'];
  const ariaLabel = restProps['aria-label'];
  const ariaLabelledBy = restProps['aria-labelledby'];

  useEffect(() => {
    if (ariaHidden === true || ariaHidden === 'true') {
      return;
    }

    if (!isPresent(ariaLabel) && !isPresent(ariaLabelledBy)) {
      warnInDevelopment(
        '[Loader] Accessible loading text is missing. Provide `aria-label` or `aria-labelledby`, or mark the loader as decorative with `aria-hidden`.',
      );
    }
  }, [ariaHidden, ariaLabel, ariaLabelledBy]);

  return (
    <span
      {...restProps}
      className={loaderVariants({ className, color, size })}
      role={restProps.role ?? 'status'}
    />
  );
}
